call plug#begin('~/.vim/plugged')
Plug 'dense-analysis/ale'
call plug#end()


"let g:ale_fixers = {
" \ 'javascript': ['eslint']
" \ }

let g:ale_linters = {
    \ 'javascript': ['eslint']
    \ }

let g:ale_javascript_eslint_executable = 'npx eslint'

let g:ale_sign_error = '❌'
let g:ale_sign_warning = '⚠️'

"let g:ale_fix_on_save = 1
